apiVersion: apps/v1
kind: Deployment
metadata:
  name: avtentikacija-deployment
  labels:
    app: shared-app
    service: avtentikacija
spec:
  replicas: 1
  selector:
    matchLabels:
      app: avtentikacija
  template:
    metadata:
      labels:
        app: avtentikacija
    spec:
      containers:
        - name: avtentikacija
          image: jantopolovec/avtentikacija:latest
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe: # Corrected field name
            httpGet:
              path: /health/liveness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3600
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3600
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: my-app-secrets
                    key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-app-secrets
                  key: JWT_SECRET
---

apiVersion: v1
kind: Service
metadata:
  name: avtentikacija-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: avtentikacija

---

apiVersion: v1
kind: Service
metadata:
  name: shared-loadbalancer-service
spec:

  type: LoadBalancer
  ports:
    - name: avtentikacija
      port: 8080
      targetPort: 8080
    - name: upravljanje-prostorov
      port: 8081
      targetPort: 8080
    - name: upravljanje-dogodkov
      port: 8082
      targetPort: 8080
  selector:
    shared: "true"