kumuluzee:
  name: avtentikacija
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  datasources:
      - jndi-name: jdbc/avtentikacija
        connection-url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        max-pool-size: 20
