kumuluzee:
  name: avtentikacija
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8080
  datasources:
      - jndi-name: jdbc/avtentikacija
        connection-url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        pool:
          max-size: 20
  health:
    servlet:
      mapping: /health/
      enabled: true
    logs:
        enabled: true
        level: INFO
        period-s: 3600
    checks:
      data-source-health-check:
        jndi-name: jdbc/avtentikacija
      disk-space-health-check:
        threshold: 100000000
  metrics:
    servlet:
      enabled: true
      mapping: /metrics
